### ISSUE TITLE
"About" feature needs to be added

### ISSUE THREAD

**Issue by iamvasuh** [named-data-mobile/ndn-photo-app#3]
information related to organization name, app version, links to forums, licence etc should be there.

**Comment by agawande** [comment]
Seems useful. I guess the organization name can be: The Named-Data Networking (NDN) Project. Since we don't have a released version yet, version can come from git commit version at the time of building (not sure how to make it happen). We don't have any forums (maybe redmine can be mentioned).

Good reminder about the license - we need to put the GPLv3 (use markdown version in a file named COPYING.md, example: https://github.com/named-data/NFD/blob/master/COPYING.md) in the repository first (can be a separate commit) and then mention in about section.
